### ISSUE TITLE
[建议]增加多国语言功能

### ISSUE THREAD

**Issue by hoozh** [qdtroy/DuiLib_Ultimate#1]
项目需要支持多国语言，官方 duilib 支持，但又有其他不少bug，用起来比较纠结

**Comment by duisharp** [comment]
收到需求

**Comment by qdtroy** [comment]
已经支持多国语言功能，请更新最新版即可

**Comment by hoozh** [comment]
已经用上了，不错。 这个问题可以关闭了

现在我自己创建了一个 CStdStringPtrMap，从xml文件加载string进来。在 QueryControlText 函数里再在CStdStringPtrMap中查找string，这样就可以支持语言文件了。 当然，希望未来版本能够官方支持加载语言文件。
