### ISSUE TITLE
CMenuWnd控件高dpi适配问题

### ISSUE THREAD

**Issue by Sarzn** [qdtroy/DuiLib_Ultimate#100]
在DuiLib/Core/UIDlgBuilder.cpp文件的第136行
if( defaultfont ) pManager->SetDefaultFont(pFontName, pManager->GetDPIObj()->Scale(size), bold, underline, italic, shared);
此处传入的size参数做了一次放大，但是该出传入的应该为字体大小，如果对字体大小做放大的话，在绘制文字时依然会对该文字做像素的放大，这就造成了文字被放大了两次，所以该处应修改为
if( defaultfont ) pManager->SetDefaultFont(pFontName, size, bold, underline, italic, shared);
size应该直接传入，不能放大之后再作为参数传入

**Comment by qdtroy** [comment]
已修正
