### ISSUE TITLE
List 头拖动问题

### ISSUE THREAD

**Issue by 821104180** [qdtroy/DuiLib_Ultimate#108]
&lt;List name="list_demo" hscrollbar="true"&gt;
&nbsp; &nbsp; &lt;ListHeader height="30" bordersize="1,0,1,1" bordercolor="#ffeeeeee"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &lt;ListHeaderItem  bkcolor="#ffffffff" text="aaa" padding="0,1,0,1" width="250"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &lt;ListHeaderItem  bkcolor="#ffffffff" text="出问题的地方" padding="0,1,3,1" width="60"/&gt;
&nbsp; &nbsp; &lt;/ListHeader&gt;
&lt;/List&gt;

在拖拽第二个表头成员时存在问题,padding="0,1,3,1"其中的3导致的问题,改为padding="0,1,0,1"会正常

**Comment by 821104180** [comment]
CListHeaderItemUI::DoEvent处进行如下修改后恢复正常
	if( event.Type == UIEVENT_MOUSEMOVE )
		{
			if( (m_uButtonState & UISTATE_CAPTURED) != 0 ) {
				RECT rc = m_rcItem;
				if( m_iSepWidth >= 0 ) {
					rc.right -= ptLastMouse.x - event.ptMouse.x + GetPadding().right ;
				}
				else {
					rc.left -= ptLastMouse.x - event.ptMouse.x +  GetPadding().left;
				}

				if( rc.right - rc.left > GetMinWidth() ) {
					m_cxyFixed.cx = rc.right - rc.left;
					ptLastMouse = event.ptMouse;
					if( GetParent() ) 
						GetParent()->NeedParentUpdate();
				}
			}
			return;
		}

**Comment by 821104180** [comment]
在	void CListHeaderItemUI::DoEvent(TEventUI& event)内做如下修改后恢复正常
                if( event.Type == UIEVENT_MOUSEMOVE )
		{
			if( (m_uButtonState & UISTATE_CAPTURED) != 0 ) {
				RECT rc = m_rcItem;
				if( m_iSepWidth >= 0 ) {
					rc.right -= ptLastMouse.x - event.ptMouse.x ;
				}
				else {
					rc.left -= ptLastMouse.x - event.ptMouse.x;
				}

				if( rc.right - rc.left > GetMinWidth() ) {
					m_cxyFixed.cx = rc.right - rc.left - GetPadding().right;//此处
					ptLastMouse = event.ptMouse;
					if( GetParent() ) 
						GetParent()->NeedParentUpdate();
				}
			}
			return;
		}

**Comment by 821104180** [comment]
滑动了横向滚动条后再进行拖拽, 还是会出现拖拽后鼠标位置与sep位置不符的情况

**Comment by qdtroy** [comment]
问题已经修正
