### ISSUE TITLE
RichEdit在Debug模式下存在一个不知道是否属于BUG的问题

### ISSUE THREAD

**Issue by xdxiaodong** [qdtroy/DuiLib_Ultimate#11]
Debug模式一个普通窗口再弹出一个模态窗口，模态窗口中的RichEdit如果在显示出来的时候进行剪切操作，当窗口关闭时就会报错。本来以为是撤销缓冲区有数据导致的，后来在窗口关闭前清空撤销缓冲区，发现还是报错。

**Comment by qdtroy** [comment]
请获取最新版测试一下
