### ISSUE TITLE
带有圆角的图片在非原尺寸渲染的时候锯齿严重

### ISSUE THREAD

**Issue by guxing** [qdtroy/DuiLib_Ultimate#110]
我这边要做一个全屏适配的客户端，需要布局中的ui在屏幕中的比例不变，所以需要对素材做缩放（素材用1080p切的，基本上适配的时候需要缩小），但无论我是改变control的width/height，还是设置外边距平铺父控件，或者启动DPI，只要控件图片不是原分辨率渲染，带有圆角的图片锯齿感特别强烈，基本上无法商用

请问这种情况有什么解决方案吗？

**Comment by guxing** [comment]
已经有解决方案了

**Comment by buqiyuan** [comment]
hello！可以请教一下你的解决方案吗？

**Comment by Calvin-Shen** [comment]
你好请问怎么解决的，目前也是 只要不是同尺寸的图片，锯齿感很严重
