### ISSUE TITLE
多级菜单无法实现点燃效果

### ISSUE THREAD

**Issue by HuaTianSoft** [qdtroy/DuiLib_Ultimate#116]
在一级菜单中, 插入二级/三级子菜单之后,一级菜单无法显示点燃色。
这是DUILIB_ULTIMATE自带的例程,也是介个样子,

![QQ截图20200906022628](https://user-images.githubusercontent.com/44983619/92311321-976a5200-efe8-11ea-9778-fcd788ed4cfa.png)

**Comment by qdtroy** [comment]
样式设置正确了吗

**Comment by qdtroy** [comment]
问题已经修正，请更新库到最新版本
