### ISSUE TITLE
使用了几天,报告几个问题

### ISSUE THREAD

**Issue by HuaTianSoft** [qdtroy/DuiLib_Ultimate#117]
首先,感谢作者作出的努力,让我这种渣渣,能够制作出好看的UI.

  使用了几天,发现了一下几个问题
    1.(Edit)编辑框问题, 经我反复测试, 发现,Edit在点击之前(未获得焦点)的时候, 它是绘制出来的一个画面(实际上不存在的,当点击之后,就会动态创建一个WIn32Edit控件, 当然,这不是问题,我发现好多的DirectUI库,都用了这种手段, 问题是, 当Edit被动态创建之后,会造成编辑框内的文本内容,上移几个像素, 在使用默认的字体(宋体吧?)时,这个问题不明显, 但是, 使用微软雅黑或其他字体时, 这个问题就非常的明显了,尤其是当Edit类型为密码类型时, 这个内容的变动就非常大了. 然后,我就去测试了一下腾讯的那个duilib(其实还有个网抑郁的DUILIB, 但是他魔改的太严重了,很多DUILIB的好东西,都被他去掉了), 发现没有这个问题, 明天我会参照腾讯的DUILIB修改修改.

  2.(RichEdit)富文本编辑框, 经我反复测试, 当一个窗口内,含有多个富文本框时, 会出现这么一个情况, 点击第一个富文本框,没有任何反应, 然后再次点击第一个富文本框, 这个时候,神奇的事情就出现了, 点击的是第一个富文本框, 然后, 确实第二个富文本框获得了输入焦点, 然后, 再次点击第一个富文本框, 它才能正常的获得输入焦点.

  3.(Menu) 菜单, 这个也是经过反复测试的,当菜单项,拥有子菜单的时候, 这个菜单项就无法正常显示点燃颜色了,  就像下图, 这是该库的Demo, 可以看到, 我选中的起始是画红框的菜单项, 但是, 该项却没有显示点燃颜色.
   
![92311321-976a5200-efe8-11ea-9778-fcd788ed4cfa](https://user-images.githubusercontent.com/44983619/92414470-ea7a0b80-f186-11ea-81b3-a2a4f93e2b11.png)

**Comment by HuaTianSoft** [comment]
哦 抱歉, 第二条,关于Riechedit的焦点问题, 已经有人发了. 作者可以忽略掉.

**Comment by qdtroy** [comment]
1、我通过Demo测试没有重现，系统和重现子例子有吗？（腾讯那份库就是直接我这个库拉过去的）
2、RichEdit这个问题，我再Duidemo中也没有重现
3、菜单问题已经修正

**Comment by HuaTianSoft** [comment]
> 1、我通过Demo测试没有重现，系统和重现子例子有吗？（腾讯那份库就是直接我这个库拉过去的）
> 2、RichEdit这个问题，我再Duidemo中也没有重现
> 3、菜单问题已经修正

好的, 我明天制作几个可以复现问题的demo,然后发给您, 您可以看看.

多谢.

这个Edit. 使用默认的字体没有任何问题, 使用了其他字体, 例如,我用了微软雅黑才出现的.

**Comment by HuaTianSoft** [comment]
顺便一提, 大佬66666. 感谢大佬的付出,.

**Comment by HuaTianSoft** [comment]
> 1、我通过Demo测试没有重现，系统和重现子例子有吗？（腾讯那份库就是直接我这个库拉过去的）
> 2、RichEdit这个问题，我再Duidemo中也没有重现
> 3、菜单问题已经修正

Edit的问题, 我搞清楚了, 是因为我在xml中, 开启了 "bktrans"这个属性.去掉这个属性,或将值设为false,则Edit没有任何问题.

您修复的Menu我还没有下载, 先不管这个问题.

Richedit这个问题, 现在是能够复现的, 但是, 这个问题, 是属于一个带有几率性的.... 十次能够复现八次吧. 有时候, 点击第一个Richedit. 但是, 焦点会跑到第二个上, 有时候, 需要点击两次, 才能获得焦点. 有时候, 点击一次,会获得输入焦点, 然后, 瞬奸就会失去, 在点击一次, 才会正常,

Demo: 链接：https://share.weiyun.com/2cET20ff 密码：8midut

**Comment by 1191050816** [comment]
我也遇到问题二了，请问怎么解决呢

**Comment by 1191050816** [comment]
> 首先,感谢作者作出的努力,让我这种渣渣,能够制作出好看的UI.
> 
> 使用了几天,发现了一下几个问题
> 1.(Edit)编辑框问题, 经我反复测试, 发现,Edit在点击之前(未获得焦点)的时候, 它是绘制出来的一个画面(实际上不存在的,当点击之后,就会动态创建一个WIn32Edit控件, 当然,这不是问题,我发现好多的DirectUI库,都用了这种手段, 问题是, 当Edit被动态创建之后,会造成编辑框内的文本内容,上移几个像素, 在使用默认的字体(宋体吧?)时,这个问题不明显, 但是, 使用微软雅黑或其他字体时, 这个问题就非常的明显了,尤其是当Edit类型为密码类型时, 这个内容的变动就非常大了. 然后,我就去测试了一下腾讯的那个duilib(其实还有个网抑郁的DUILIB, 但是他魔改的太严重了,很多DUILIB的好东西,都被他去掉了), 发现没有这个问题, 明天我会参照腾讯的DUILIB修改修改.
> 
> 2.(RichEdit)富文本编辑框, 经我反复测试, 当一个窗口内,含有多个富文本框时, 会出现这么一个情况, 点击第一个富文本框,没有任何反应, 然后再次点击第一个富文本框, 这个时候,神奇的事情就出现了, 点击的是第一个富文本框, 然后, 确实第二个富文本框获得了输入焦点, 然后, 再次点击第一个富文本框, 它才能正常的获得输入焦点.
> 
> 3.(Menu) 菜单, 这个也是经过反复测试的,当菜单项,拥有子菜单的时候, 这个菜单项就无法正常显示点燃颜色了, 就像下图, 这是该库的Demo, 可以看到, 我选中的起始是画红框的菜单项, 但是, 该项却没有显示点燃颜色.
> 
> ![92311321-976a5200-efe8-11ea-9778-fcd788ed4cfa](https://user-images.githubusercontent.com/44983619/92414470-ea7a0b80-f186-11ea-81b3-a2a4f93e2b11.png)

请问问题二怎么解决呢
