### ISSUE TITLE
Richedit/Edit 问题复现

### ISSUE THREAD

**Issue by HuaTianSoft** [qdtroy/DuiLib_Ultimate#118]
Edit的问题, 我搞清楚了, 是因为我在xml中, 开启了 "bktrans"这个属性.去掉这个属性,或将值设为false,则Edit没有任何问题.

您修复的Menu我还没有下载, 先不管这个问题.

Richedit这个问题, 现在是能够复现的, 但是, 这个问题, 是属于一个带有几率性的.... 十次能够复现八次吧. 有时候, 点击第一个Richedit. 但是, 焦点会跑到第二个上, 有时候, 需要点击两次, 才能获得焦点. 有时候, 点击一次,会获得输入焦点, 然后, 瞬奸就会失去, 在点击一次, 才会正常,

Demo: 链接：https://share.weiyun.com/2cET20ff 密码：8midut

**Comment by qdtroy** [comment]
你发我demo还是不能重现，我的系统版本如下：
![image](https://user-images.githubusercontent.com/8225520/92564536-e8f63380-f2ab-11ea-9cd9-99bb234bcfcf.png)

**Comment by HuaTianSoft** [comment]
纳尼....  
我的系统是 WINDOWS 10 专业版 64位  1909 18363.1049.
晚上回家后, 我重装一下系统试试, 另,您可以看一下这个视频, 这是我录制的复现问题的视频. 现在是百分百能够触发这个问题了000  之前还是几率性的， 现在是百分百.. 

链接：https://share.weiyun.com/MGiGV7qH 密码：a55kep

**Comment by 1191050816** [comment]
请问怎么解决的呢，我也复现了，很难受

**Comment by 1191050816** [comment]
// Set focus to first control?
            //if( m_bFocusNeeded ) {
            //    SetNextTabControl();
            //}
我把这个注释掉，问题就没了uimanager.cpp

**Comment by 1191050816** [comment]
点击第一个richedit的时候，触发到了richedit的setfocus，然后一会又触发了killfocus，就是这里触发的

**Comment by 1191050816** [comment]
好像是和我界面中使用到tablayout有关

**Comment by KnIfER** [comment]
确实 100% 触发，只有首次启动有。和 tablayout 无关。

**Comment by qdtroy** [comment]
> 和我界面中使用到tablayout有关

焦点转移的逻辑有点问题
