### ISSUE TITLE
Edit bug反馈

### ISSUE THREAD

**Issue by HuaTianSoft** [qdtroy/DuiLib_Ultimate#119]
bug位置 https://github.com/qdtroy/DuiLib_Ultimate/blob/3067ee6942c85886daf71e3411a6b46fb69066be/DuiLib/Control/UIEdit.cpp#L166

修正为 else if( uMsg == WM_KEYDOWN && wParam == VK_RETURN ){

**Comment by qdtroy** [comment]
这里是什么问题呢？
