### ISSUE TITLE
建议Edit增加一个粘贴消息WM_PASTE消息的事件转发

### ISSUE THREAD

**Issue by xdxiaodong** [qdtroy/DuiLib_Ultimate#12]
目前我自己在LRESULT CEditWnd::HandleMessage(UINT uMsg, WPARAM wParam, LPARAM lParam)下增加了以下代码实现的粘贴消息转发  
else if (uMsg == WM_PASTE)
		{
			bHandled = FALSE;
			if (m_bInit)
			{
				if (m_pOwner != NULL)
				{
					bool handled = false;
					if (m_pOwner->GetName().Find(_T("_bHandled_")) > 0)
					{
						//当name内包含_bHandled_时在转发粘贴消息
						handled = true;
					}
					if (handled)
					{
						//记录下编辑框的窗口句柄
						HWND hwnd = m_pOwner->m_pWindow->m_hWnd;
						//转发编辑框粘贴消息
						m_pOwner->GetManager()->SendNotify(m_pOwner, _T("edit_paste"));
						//当编辑框的窗口句柄失去焦点后也就是窗口句柄无效时就需要拦截粘贴消息
						if (!::IsWindow(hwnd))
						{
							bHandled = TRUE;
							return 0;
						}
					}
					
				}
			}
		}

我这种做法并不具备通用性。

**Comment by qdtroy** [comment]
这种使用方法都用在什么情况下呢？

**Comment by xdxiaodong** [comment]
其中一个场景：编辑框需要区分用户是粘贴还是输入的，比如判断用户粘贴过来的内容是否为一个URL，然后决定是否让粘贴内容显示到编辑框。
