### ISSUE TITLE
鼠标右键bug

### ISSUE THREAD

**Issue by Awin-L** [qdtroy/DuiLib_Ultimate#121]
主窗口弹出子窗口，鼠标右键子窗口一个按钮控件，鼠标保持按下状态不变并拖动主窗口松开鼠标，这是主窗口被卡死，只有再点击子窗口才会恢复正常。
		case WM_RBUTTONUP:
			{
				POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };
				m_ptLastMousePos = pt;
				m_pEventClick = FindControl(pt);
				if(m_pEventClick == NULL) break;
				ReleaseCapture();
				TEventUI event = { 0 };
				event.Type = UIEVENT_RBUTTONUP;
				event.pSender = m_pEventClick;
				event.wParam = wParam;
				event.lParam = lParam;
				event.ptMouse = pt;
				event.wKeyState = (WORD)wParam;
				event.dwTimestamp = ::GetTickCount();
				m_pEventClick->Event(event);
			}
			break;
问题代码为ReleaseCapture();当鼠标抬起不在一个窗口时，无法调用该函数，将该函数放在m_pEventClick = FindControl(pt);之前即可。

**Comment by qdtroy** [comment]
已经修正
