### ISSUE TITLE
配套的DuiDesigner界面设计工具有吗？

### ISSUE THREAD

**Issue by libaineu2004** [qdtroy/DuiLib_Ultimate#123]
googlecode.com上391版本，可以找到早期版本的DuiDesigner
https://github.com/wamaqa/DuiDesigner/tree/master/DuiDesigner

那么，请问：
有没有和DuiLib_Ultimate相配套的DuiDesigner？

**Comment by qdtroy** [comment]
没有设计器，原有版本的设计器也已经废弃

**Comment by libaineu2004** [comment]
> 没有设计器，原有版本的设计器也已经废弃

我在github上找到了duilib的第三方ui界面设计器：
https://github.com/xfcanyue/DuiLib_DuiEditor
https://blog.csdn.net/mmcanyu/article/details/106758857
