### ISSUE TITLE
RichEdit 高DPI字体未适配BUG

### ISSUE THREAD

**Issue by hwl19951007** [qdtroy/DuiLib_Ultimate#126]
此处代码查找类名，使用的是"RichEditUI"
https://github.com/qdtroy/DuiLib_Ultimate/blob/3067ee6942c85886daf71e3411a6b46fb69066be/DuiLib/Core/UIManager.cpp#L2161
但RichEdit控件的GetClass如下：
https://github.com/qdtroy/DuiLib_Ultimate/blob/3067ee6942c85886daf71e3411a6b46fb69066be/DuiLib/Control/UIRichEdit.cpp#L1105-L1108
实际返回值为：
https://github.com/qdtroy/DuiLib_Ultimate/blob/3067ee6942c85886daf71e3411a6b46fb69066be/DuiLib/Core/UIDefine.h#L280

查找使用的类名与实际返回的类名不符，导致所有DPI下字体大小都一致，没有适配DPI。
同样查找RichEdit控件的还有一处是https://github.com/qdtroy/DuiLib_Ultimate/blob/3067ee6942c85886daf71e3411a6b46fb69066be/DuiLib/Core/UIManager.cpp#L859
我没有校验，但应该也是有问题的。

**Comment by qdtroy** [comment]
问题已经修正
