### ISSUE TITLE
菜单控件存在一个小问题

### ISSUE THREAD

**Issue by xdxiaodong** [qdtroy/DuiLib_Ultimate#13]
动态菜单弹出来后，鼠标悬停到某一个菜单项的时候，按下鼠标左键（不松开鼠标左键），鼠标往下移动，滑动到下个菜单项的时候松开鼠标左键，这时候响应的菜单时间是鼠标按下去的时候的菜单项的，而非鼠标指针所在位置的菜单项的。  
建议的方法：  
1.鼠标释放的时候判断下是不是按下时所记录的菜单项，不是的话就不需要响应菜单事件了。  
2.鼠标释放的时候在转发菜单时间的时候转发鼠标指针所在菜单项的，而非鼠标左键按下时的菜单项的。

**Comment by qdtroy** [comment]
谢谢反馈
