### ISSUE TITLE
CListUI隐藏列时,滚动条计算错误

### ISSUE THREAD

**Issue by qq82850696** [qdtroy/DuiLib_Ultimate#136]
因为CListUI列多达36列,加了个隐藏列功能,隐藏后发现列没有那么多,但是水平滚动条还在,经过调试发现只要在计算横坐标大小的时候,忽略不显示的列就行,经测试是完全可以的.相同的思路,cXY.cy的计算是否也要加上判断列是否显示的判断,以下是修改后的代码,是否可行?

SIZE CListHeaderUI::EstimateSize(SIZE szAvailable)
	{
		SIZE cXY = { 0, m_cxyFixed.cy };
		if (cXY.cy == 0 && m_pManager != NULL) {
			for (int it = 0; it < m_items.GetSize(); it++) {
				cXY.cy = MAX(cXY.cy, static_cast<CControlUI*>(m_items[it])->EstimateSize(szAvailable).cy);
			}
			int nMin = m_pManager->GetDefaultFontInfo()->tm.tmHeight + 6;
			cXY.cy = MAX(cXY.cy, nMin);
		}

		for (int it = 0; it < m_items.GetSize(); it++) {
			//  [ 2021/10/14 17:54:14]修复列隐藏滚动条计算问题
			CControlUI* pControl = static_cast<CControlUI*>(m_items[it]);
			if (pControl && pControl->IsVisible())
			{
				cXY.cx += pControl->EstimateSize(szAvailable).cx;
			}
		}

		if (cXY.cx < szAvailable.cx) cXY.cx = szAvailable.cx;
		return cXY;
	}

**Comment by qdtroy** [comment]
已经修复
