### ISSUE TITLE
容器类增加重载函数,便于操作

### ISSUE THREAD

**Issue by qq82850696** [qdtroy/DuiLib_Ultimate#142]
`CControlUI* CContainerUI::GetItemAt(LPCTSTR pszItem, bool bCase /*= false*/) const
	{
		for (int it = 0; it < m_items.GetSize(); it++)
		{
			auto pControl= static_cast<CControlUI*>(m_items[it]);
			if (pControl)
			{
				if (bCase)
				{
					if (!pControl->GetText().Compare(pszItem))
					{
						return pControl;
					}
				} 
				else
				{
					if (!pControl->GetText().CompareNoCase(pszItem))
					{
						return pControl;
					}
				}
			}
		}
		return nullptr;
	}

	int CContainerUI::GetItemIndex(LPCTSTR pszItem, bool bCase /*= false*/) const
	{
		int iIndex = -1;
		for (int it = 0; it < m_items.GetSize(); it++) 
		{
			 auto pControl = static_cast<CControlUI*>(m_items[it]);
			if (bCase)
			{
				if (!pControl->GetText().Compare(pszItem))
				{
					iIndex = it;
					break;

				}
			}
			else
			{
				if (!pControl->GetText().CompareNoCase(pszItem))
				{
					iIndex = it;
					break;

				}
			}
		}

		return iIndex;
	}
bool CContainerUI::Remove(LPCTSTR pszItem, bool bCase /*= false*/)
	{
		for (int it = 0; it < m_items.GetSize(); it++) 
		{
			bool bCompare = false;
			auto pControl = static_cast<CControlUI*>(m_items[it]);
			if (bCase)
			{
				bCompare = (!pControl->GetText().Compare(pszItem));
			} 
			else
			{
				bCompare = (!pControl->GetText().CompareNoCase(pszItem));
			}

			if (bCompare) {
				NeedUpdate();
				if (m_bAutoDestroy) {
					if (m_bDelayedDestroy && m_pManager) m_pManager->AddDelayedCleanup(pControl);
					else delete pControl;
				}
				return m_items.Remove(it);
			}
		}
		return false;
	}
`

**Comment by qdtroy** [comment]
通过标题操作UI，非通用操作，暂不支持
