### ISSUE TITLE
下拉框增加重载函数Remove

### ISSUE THREAD

**Issue by qq82850696** [qdtroy/DuiLib_Ultimate#143]
bool CComboUI::Remove(LPCTSTR pszItem, bool bCase /*= false*/)
	{
		bool bRet = false;
        int iIndex = GetItemIndex(pszItem, bCase);
        if (iIndex == -1) return false;
		return RemoveAt(iIndex);
	}

**Comment by qdtroy** [comment]
通过标题操作UI，非通用操作，暂不支持
