### ISSUE TITLE
在外接显示器上，最大化窗体时会出问题

### ISSUE THREAD

**Issue by hoozh** [qdtroy/DuiLib_Ultimate#15]
用duidemo程序测试，在外接显示器上点击标题栏上的最大化按钮后，窗体只有一部分显示在了两个显示器的中间位置

**Comment by qdtroy** [comment]
问题已经修复，请更新最新代码即可

**Comment by hoozh** [comment]
@qdtroy 测了了最新的代码，好像还是有问题

用duidemo 和 transwnd 测试，win7/win8 64位，主显示器1440x900，扩展显示器1920x1080

1. 在主显示器上，最大化有时能成功，有时界面只是移动到屏幕的左上角，并没有最大化，而且最小化、最大化、关闭按钮都消失了。

ps: 拔掉扩展显示器也是如此

2. 在扩展显示器上，最大化有时能成功，但是貌似窗口宽度超出了屏幕范围，右侧一部分界面消失。不成功的时候，现象和主显示器上一样。


还没空研究代码，先报告一下，嗯
