### ISSUE TITLE
UIRing内存泄漏

### ISSUE THREAD

**Issue by xxasm** [qdtroy/DuiLib_Ultimate#159]
![1](https://user-images.githubusercontent.com/31958588/193773532-6470bb80-5738-4ffc-8349-0174c8ddcb75.PNG)
![2](https://user-images.githubusercontent.com/31958588/193773545-ab147fe6-eda3-43cf-9d82-1f88093be700.PNG)

TImageInfo* pImageInfo = CRenderEngine::GdiplusLoadImage(GetBkImage());
TImageInfo* pImageInfo 在析构函数没有释放，

可以保存这个结构pImageInfo ，然后在析构函数释放
CRenderEngine::FreeImage(TImageInfo* pinfo);

**Comment by qdtroy** [comment]
谢谢反馈，已经修复
