### ISSUE TITLE
向控件发送 Notify 函数 SendNotify 异步情况，不支持 虚拟窗口 virtualwnd 的问题，从duilib原版同步一句代码过来，就可以了

### ISSUE THREAD

**Issue by HackerJLY** [qdtroy/DuiLib_Ultimate#175]
![image](https://github.com/qdtroy/DuiLib_Ultimate/assets/3407061/00c17285-a124-4f02-8207-29c66affdb26)

**Comment by qdtroy** [comment]
感谢反馈，问题已经修复。
