### ISSUE TITLE
多语言接口BUG

### ISSUE THREAD

**Issue by hlxxiang** [qdtroy/DuiLib_Ultimate#18]
在支持多语言的情况下如果程序有弹出对话框，并且这个对话框继承自 WindowImplBase，当对对话框销毁后，主程序再一次弹出对话框或者含有菜单就会崩溃。
WindowImpBase::OnCreateTe()
{
......
// 多语言接口
	CResourceManager::GetInstance()->SetTextQueryInterface(this);   ///这个会被销毁
....
}
每次WindowImpBase集成的窗体每次销毁之后都需要重新设置m_pQuerypInterface
建议：
     CResourceManager 不应该设置成单例

     CDuiString CControlUI::GetText() const
    {
        if (!IsResourceText())
            return m_sText;
        //return CResourceManager::GetInstance()->GetText(m_sText);
        return  m_pManager->GetResouceManager()->GetText(m_sText)
    }

**Comment by hlxxiang** [comment]
`LRESULT WindowImplBase::OnSetFocus(UINT /*uMsg*/, WPARAM /*wParam*/, LPARAM /*lParam*/, BOOL& bHandled)
{
    CResourceManager::GetInstance()->SetTextQueryInterface(this);
	bHandled = FALSE;
	return 0;
}`
这样也可以解决  能防止别人不会注意到this可能被销毁

**Comment by qdtroy** [comment]
问题修复了，获取最新版就可以了
