### ISSUE TITLE
WindowImplBase下的GetResourceType和GetResourceID无实现, 与原版不兼容

### ISSUE THREAD

**Issue by HHsomeHand** [qdtroy/DuiLib_Ultimate#181]
今天使用duilib的时候遇到的, 原本想打包zip到exe, 但是发现GetResourceType和GetResourceID无实现, UILIB_RESOURCETYPE的名称也变成了UILIB_RESTYPE

**Comment by qdtroy** [comment]
旗舰版使用的统一资源管理器，不需要每个Window单独配置资源类型和ID，使用方式参考duidemo里面的InitResource接口
