### ISSUE TITLE
这个版本的duilib对于不同dpi下图片的问题

### ISSUE THREAD

**Issue by Calvin-Shen** [qdtroy/DuiLib_Ultimate#183]
必须是起名@125.png @150.png @175.png 。。。这样的么？
有没有方式我只用高清图片比如：x2的图片 自动缩放到对应需要的大小么。这样就不用放同一图片的不同大小的。
就像qt 中label 能scaletocontents那样。图片也不会有锯齿。

目前我用x2的图片，在1.5倍的dpi下  图片挺模糊的。
![image](https://github.com/user-attachments/assets/eb725b84-ebc9-4cc2-b639-d32fa0fc94c0)

**Comment by qdtroy** [comment]
DPI适配时，图片名称和尺寸都是固定的
