### ISSUE TITLE
TroyBrowser 编译的时候，报错。

### ISSUE THREAD

**Issue by kuafuwang** [qdtroy/DuiLib_Ultimate#19]
MainWnd.cpp(75): error C2065: “m_PaintManager”: 未声明的标识符
1>MainWnd.cpp(75): error C2228: “.FindControl”的左边必须有类/结构/联合
1>  MainWnd.cpp(75): note: 类型是“unknown-type”
1>MainWnd.cpp(76): error C2065: “m_PaintManager”: 未声明的标识符
1>MainWnd.cpp(76): error C2228: “.FindControl”的左边必须有类/结构/联合
1>  MainWnd.cpp(76): note: 类型是“unknown-type”

**Comment by kuafuwang** [comment]
你为什么要把原来duilib的m_PaintManager 改成m_pm呢？

**Comment by qdtroy** [comment]
已经修复
