### ISSUE TITLE
缺少工程项目

### ISSUE THREAD

**Issue by KingYoung87** [qdtroy/DuiLib_Ultimate#21]
1下载之后，打开Duilib.sln,提示缺少Mfcapp还有TroyControl工程项。
2编译完毕之后，运行demo，有的demo无法运行。

**Comment by qdtroy** [comment]
MFCApp和TroyControls暂未放开，请使用Debug模式编译运行，如果使用Release，需要自己压缩Skins目录对应的皮肤资源替换项目Res目录下的资源包
