### ISSUE TITLE
菜单控件的一个小问题

### ISSUE THREAD

**Issue by gaodeng** [qdtroy/DuiLib_Ultimate#22]
菜单控件弹出后会获取窗口焦点，当失去焦点的时候菜单消失。如果这个菜单控件是输入框的右键菜单的话，点击右键菜单，输入框焦点就消失了，选中的文本就变灰了，跟系统的菜单行为不一致。

**Comment by qdtroy** [comment]
菜单是通过窗口来实现的，行为和系统有点不一样
