### ISSUE TITLE
WindowImplBase 类中的 OnSysCommand 函数实现是不是有点过时了？

### ISSUE THREAD

**Issue by hoozh** [qdtroy/DuiLib_Ultimate#23]
duidemo 的 主界面类重写了 OnSysCommand，工作正常。 

不重写的话，会导致问题：**界面最大化后再最小话，点击任务栏图标，界面无法恢复到最大化状态，而且也无法再最大化。**

**Comment by qdtroy** [comment]
问题已经修正，请获取新版，谢谢反馈
