### ISSUE TITLE
菜单使用透明窗口时，有时显示不全。

### ISSUE THREAD

**Issue by gaodeng** [qdtroy/DuiLib_Ultimate#27]
![yh7a9d3tt 99 9b u3dr f](https://cloud.githubusercontent.com/assets/1118249/16719245/a76902d6-475a-11e6-9780-f2db6d89bf6f.png)
![qq 20160711113110](https://cloud.githubusercontent.com/assets/1118249/16719280/fe9d280c-475a-11e6-835d-48d568a00174.png)

如图。菜单使用透明窗口时，有时显示不全。这个问题在win10 和 xp下没有，win7下连续点击弹出菜单按钮时经常发生。但是菜单没有显示的部分，不影响响应菜单点击事件。

重现方式
1.菜单窗口 bktrans="true"
2.duidemo MainWnd.h 调整一下菜单弹出点。
![qq 20160711113708](https://cloud.githubusercontent.com/assets/1118249/16719341/d2f8c822-475b-11e6-8b76-42d0e74ae074.png)
3.编译，在win7下运行 duidemo,连续点击弹出菜单按钮，

**Comment by lion117** [comment]
![q -20161122182418](https://cloud.githubusercontent.com/assets/3996029/20520215/edff85c2-b0e0-11e6-8d03-1001dded3bd8.png)

## 笨的解决方案
对 UImenu里面的 **MoveWindow()**  FALSE 修改 为TRUE . 修改为强制要求重绘. 每次重新调整窗口, 都要求重绘之.
