### ISSUE TITLE
请教下关于窗口嵌套的问题

### ISSUE THREAD

**Issue by fawdlstty** [qdtroy/DuiLib_Ultimate#28]
问下高手，a.xml窗口嵌套b.xml窗口，然后再在子窗口里面嵌套c.xml窗口。我在a窗口的windowinit事件中加载b.xml，这时候成功，代码大致如下container->Add (builder.Create (_T ("b.xml"), (UINT) 0, this, &m_pm));
这时候加载到主窗口了，然后再在子窗口里面加载c.xml，这时候爆了一个错误，主要地方大概在UIMarkup.cpp里面的下面这段代码中：
CMarkup::XMLELEMENT* CMarkup::_ReserveElement()
{
    if( m_nElements == 0 ) m_nReservedElements = 0;
    if( m_nElements >= m_nReservedElements ) {
        m_nReservedElements += (m_nReservedElements / 2) + 500;
        m_pElements = static_cast<XMLELEMENT*>(realloc(m_pElements, m_nReservedElements * sizeof(XMLELEMENT)));
    }
    return &m_pElements[m_nElements++];
}
m_nElements这个的值为20，m_nReservedElements这个的值为500，m_pElements的值为NULL，因为是取地址符的原因结果神奇的没报错，错误地点在其他离得比较远的地方，断点调试了一会才发现这个问题。这个代码如何解决呢？

**Comment by fawdlstty** [comment]
精简化的源代码大概如下
virtual void Notify (TNotifyUI& msg) {
    if (msg.sType == _T ("windowinit")) {
        CDialogBuilder builder;
        CContainerUI *container = static_cast<CContainerUI*>(m_pm.FindControl (_T ("tabM")));
        for (int i = 0; i < N; ++i) {
            container->Add (builder.Create (_T ("b.xml"), (UINT) 0, this, &m_pm));
            CContainerUI *group2 = static_cast<CContainerUI*>(m_pm.FindControl (_T ("tab0")));//b.xml里面的东西，这个获取成功
            group2->Add (builder.Create (_T ("b.xml"), (UINT) 0, this, &m_pm));//在b.xml里面插入新窗体
        }
    }
}
试过各种不同的方法，每次Create时新建builder对象也不行

**Comment by GitHub63419875** [comment]
窗口嵌套，子部分应该在CreateControl（）接口里创建。
不应该在windowinit消息内部处理。

**Comment by fawdlstty** [comment]
我并不是需要创建自定义控件，而是全部为标准控件，WindowImplBase都直接返回的

**Comment by GitHub63419875** [comment]
给子窗口取个别名，它就是自定义控件。
[XML嵌套](http://www.cnblogs.com/Alberl/p/3381820.html)

**Comment by GitHub63419875** [comment]
还有种方案
用ChildLayout

**Comment by GitHub63419875** [comment]
[ChildLayout](http://blog.csdn.net/zhuhongshu/article/details/38531447)

**Comment by fawdlstty** [comment]
我现在是不想弄成自定义控件，我只是想自动添加新的标签页，就是TabLayout，在这里面动态添加一堆Option和动态标签页，上面第一个思路目测太麻烦，第二个思路插入的位置不对。另外功能本身没问题，也就是说第一层的动态标签页可以插入并测试成功，只有在第一层里面插入第二层的时候才有问题

**Comment by GitHub63419875** [comment]
布局位置不对应该能解决，建议使用ChildLayout方案。
windowinit消息是在窗口布局建立完成后，第一次WM_PAINT前发出的。你这种用法与框架思维不合，后面可能还会爆出其他问题。

**Comment by fawdlstty** [comment]
我如果在ChildLayout里面插入一堆窗口，怎么把它们移动到TabLayout里面？毕竟数量不定，用固定数量的ChildLayout不行，另外必须是TabLayout的子控件才能切换，子控件的子控件不行

**Comment by fawdlstty** [comment]
另外，我就是得等窗口布局建立以后，第一次WM_PAINT前创建才行，如果已经显示出来了，那么会闪屏，如果在窗口布局还没建立，那么找不到控件的名称了，这个名称用来作为插入点

**Comment by GitHub63419875** [comment]
按你的意思“元素数量值”获取是比窗口创建先一步发生，即如此你可以试试在CDialogBuilder构建窗口过程中动态创建你需要的部分。（通过一个无效控件名字，触发CreateControl函数，产生一个动态创建的机会）。
方案不一定行，没实验过。

**Comment by GitHub63419875** [comment]
这个触发CreateControl的自定义名称最好放在xml最后方。后于TabLayout构建。

**Comment by fawdlstty** [comment]
我还是等下一个高手算了，，

**Comment by qdtroy** [comment]
这个和窗口嵌套没关系，你直接加载c.xml试试

**Comment by fawdlstty** [comment]
直接加载或嵌套一层没有问题，一旦嵌套两层那就有问题
