### ISSUE TITLE
同一pFn用&pFn得到的void*地址可能不同，请教原因？

### ISSUE THREAD

**Issue by Gh72** [qdtroy/DuiLib_Ultimate#29]
同一类成员指针pFn用&pFn得到的void_地址可能不同，请教原因？加入int_中间转换则ok。
正常DUILIB版本下不会碰到这个BUG，我是扩展了事件源的使用（带条件判断的委托调用），才碰到这个bug的。

`template <class O, class T>
class CDelegate : public CDelegateBase
{
    typedef bool (T::\* Fn)(void_);
public:
    // 不同调用情况下，同一pFn用&pFn得到的void_可能不同;原因未知
    //CDelegate(O\* pObj, Fn pFn) : CDelegateBase(pObj, (void\* )(&pFn)), m_pFn(pFn) { }  
    CDelegate(O\* pObj, Fn pFn) : CDelegateBase(pObj, (void\* )(\* ((int\* )((void\* )&pFn)))), m_pFn(pFn) { }
    CDelegate(const CDelegate& rhs) : CDelegateBase(rhs) { m_pFn = rhs.m_pFn; } 
    virtual CDelegateBase\* Copy() const { return new CDelegate(*this); }

protected:
    virtual bool Invoke(void\* param)
    {
        O\* pObject = (O_) GetObject();
        return (pObject->_m_pFn)(param); 
    }  

private:
    Fn m_pFn;
};`

**Comment by GitHub63419875** [comment]
pFn为类成员指针

**Comment by IULOVE** [comment]
我也遇到 用 const  &  竟然和  本体不一样 ··· CPaintManager 这个
