### ISSUE TITLE
关于float的问题

### ISSUE THREAD

**Issue by lovesnow** [qdtroy/DuiLib_Ultimate#37]
把一个控件设置为float后，再设置pos，只能放到父控件的左边位置，能不能设置pos为负值，放到父控件的右边

**Comment by lovesnow** [comment]
@gaodeng @qdtroy

**Comment by lion117** [comment]
float 模式下, 默认都是从左计算坐标点. 往右的计算, 都是自己手工计算处理出来滴. 
在非float模式下, 可以使用padding 进行右靠边处理

**Comment by qdtroy** [comment]
@lovesnow 可以使用floatalign属性来设置对齐方式
