### ISSUE TITLE
GifAnim控件加载gif图片后，关闭该窗口，内存没有释放

### ISSUE THREAD

**Issue by cuiguanghui** [qdtroy/DuiLib_Ultimate#38]
发现该方法有些问题。成功加载图片后，该条件不会被执行	
		if(!pImg || pImg->GetLastStatus() != Gdiplus::Ok)
		{
			pStm->Release();
			::GlobalUnlock(hMem);
			return 0;
		}
所以也就无法释放资源，建议把pStm和hMem设置为该对象的一个私有变量，DeleteGif()中释放
Gdiplus::Image* CGifAnimUI::LoadGifFromMemory( LPVOID pBuf,size_t dwSize )
	{
		HGLOBAL hMem = ::GlobalAlloc(GMEM_FIXED, dwSize);
		BYTE* pMem = (BYTE*)::GlobalLock(hMem);

		memcpy(pMem, pBuf, dwSize);

		IStream* pStm = NULL;
		::CreateStreamOnHGlobal(hMem, TRUE, &pStm);
		Gdiplus::Image *pImg = Gdiplus::Image::FromStream(pStm);
		if(!pImg || pImg->GetLastStatus() != Gdiplus::Ok)
		{
			pStm->Release();
			::GlobalUnlock(hMem);
			return 0;
		}
		return pImg;
	}

**Comment by qdtroy** [comment]
获取最新版本测试一下
