### ISSUE TITLE
HiDpi test  放大后 菜单绘制不全

### ISSUE THREAD

**Issue by IULOVE** [qdtroy/DuiLib_Ultimate#39]
__
![image](https://cloud.githubusercontent.com/assets/14193276/20551332/2dbe4998-b17a-11e6-9019-5e70789b443f.png)

win7 64位  那些图标也有问题

**Comment by IULOVE** [comment]
不放大也会··
![image](https://cloud.githubusercontent.com/assets/14193276/20551615/26148c54-b17d-11e6-9f00-9b3dac87ea4b.png) 点击这里会很容易出现

**Comment by gaodeng** [comment]
可能和 issue  #27 是同一个问题。
