### ISSUE TITLE
Treeview node 选中问题

### ISSUE THREAD

**Issue by IULOVE** [qdtroy/DuiLib_Ultimate#40]
![image](https://cloud.githubusercontent.com/assets/14193276/20603222/7b91a364-b29b-11e6-80bb-bef42b855174.png)
TreeViewUI 这个应该是BUG 你看这个例子 继承的也是 list  他能选中  TreeView 这个就不行 他怎么返回到CButtonUI::DoEvent 的···

folderattr="width=&quot;0&quot; float=&quot;true&quot;"  找到了原来是这个属性导致的·· 这算BUG 吗

**Comment by qdtroy** [comment]
这个是属性定制，不是Bug
