### ISSUE TITLE
编译后的程序运行都是崩溃

### ISSUE THREAD

**Issue by nmgwddj** [qdtroy/DuiLib_Ultimate#41]
![2016-11-29_160125](https://cloud.githubusercontent.com/assets/13995319/20701289/17b89310-b64d-11e6-92b7-8c322b4e0b91.png)

**Comment by qdtroy** [comment]
浏览器Demo请使用VS2010编译Debug版本，不适用于其它编译器

**Comment by nmgwddj** [comment]
![vs2010](https://cloud.githubusercontent.com/assets/13995319/21086781/a8fef000-c05a-11e6-9a45-6e01ecbfb302.gif)
