### ISSUE TITLE
调色板控件:如果窗口bktrans=“true”,控件显示错误，下面变空。

### ISSUE THREAD

**Issue by gmshizhu4727** [qdtroy/DuiLib_Ultimate#43]
如果窗口bktrans=“true”,控件显示错误，下面变空。

**Comment by qdtroy** [comment]
我测试duidemo是正常的，有问题QQ给我截图看下

**Comment by gmshizhu4727** [comment]
由于我不知道你QQ多少，我给你发下duidemo窗口xml文件:main.xml，我只是把标签windows的bktrans属性设成true，ColorPalette控件下边背景就彻底变空。如果方便，麻烦告诉下你QQ，我上传了截图。谢谢了！
![menxml](https://cloud.githubusercontent.com/assets/24453080/21302723/36e7864a-c5f4-11e6-8660-9ceb7ec6265f.png)
![default](https://cloud.githubusercontent.com/assets/24453080/21302724/374ddeae-c5f4-11e6-8523-c0a7a5c71885.png)

**Comment by qdtroy** [comment]
qq 656067418

**Comment by qdtroy** [comment]
已经修复，请获取最新版
