### ISSUE TITLE
边框阴影bug

### ISSUE THREAD

**Issue by horatii** [qdtroy/DuiLib_Ultimate#48]
以隐藏方式创建窗口，当显示窗口时会导致阴影无效。
![qq 20170309201455](https://cloud.githubusercontent.com/assets/11205116/23749973/c73940bc-0505-11e7-91cb-66d12ccf71f7.png)

**Comment by horatii** [comment]
return WindowImplBase::Create(
		nullptr,
		TITLE_NAME,
		UI_WNDSTYLE_FRAME &~WS_MAXIMIZEBOX &~WS_VISIBLE,
		WS_EX_WINDOWEDGE | WS_EX_TOOLWINDOW,
		0, 0, 0, 0);

**Comment by horatii** [comment]
::SetWindowPos(
		m_hWnd, 
		NULL, 
		point.x, 
		point.y, 
		-1, 
		-1, 
		SWP_NOSIZE | SWP_NOZORDER | SWP_SHOWWINDOW);

窗口显示的代码，没有使用 Showwindow来做

**Comment by horatii** [comment]
使用Showwindow正常，我想找个bug是阴影窗口在处理 窗口显示的消息时只处理 WM_SHOWWINDOW 没有处理 WM_WINDOWPOSCHANGED 消息中附带 显示窗口的情况

**Comment by horatii** [comment]
代码 UIShadow.cpp 126 行在处理WM_WINDOWPOSCHANGED消息时应该加入判断 WINDOWPOS 的flags代码，如果flags标志中有 SWP_SHOWWINDOW或者SWP_HIDEWIDNOW时设置自己的m_status

**Comment by qdtroy** [comment]
已经修复u
