### ISSUE TITLE
richedit释放奔溃bug

### ISSUE THREAD

**Issue by horatii** [qdtroy/DuiLib_Ultimate#50]
### 运行堆栈如下：
![qq 20170315140549](https://cloud.githubusercontent.com/assets/11205116/23935820/322ae6a0-0989-11e7-893a-5a7090647a6e.png)

### 再现
关闭窗口时并且调用窗口的析构函数会有几率引起此 
触发的消息 : EN_SAVECLIPBOARD		0x0708

**Comment by qdtroy** [comment]
问题怎么重现？
