### ISSUE TITLE
Control控件bordersize Bug

### ISSUE THREAD

**Issue by cmtltmcl** [qdtroy/DuiLib_Ultimate#53]
bordersize="5,15,10,20"  这样设置不相等的边框宽度时，出现椭圆。

![image](https://cloud.githubusercontent.com/assets/13461698/25331633/532ee0f2-2916-11e7-9aa4-1557393fe169.png)

**Comment by qdtroy** [comment]
收到反馈，尽快修复

**Comment by qdtroy** [comment]
bordersize不等时请不要和roundcorner混用
