### ISSUE TITLE
菜单项点击之后无法获得相应的信息

### ISSUE THREAD

**Issue by woosky92** [qdtroy/DuiLib_Ultimate#61]
`if (CMenuWnd::GetGlobalContextMenuObserver().GetManager() != NULL)
{
                  CMenuWnd::SetClickedMenuName(GetName());
		PostMessage(CMenuWnd::GetGlobalContextMenuObserver().GetManager()->GetPaintWindow(), WM_MENUCLICK, NULL, (LPARAM)(GetChecked() ? TRUE : FALSE));
				}`
这里的菜单项点击之后无法获得相应的信息

**Comment by qdtroy** [comment]
测试可以的，可以通过设置的全局信息去获取
