### ISSUE TITLE
UIMANAGER.cpp 32 33行 MK_LBUTTON MK_RBUTTON是不是反了

### ISSUE THREAD

**Issue by flhang** [qdtroy/DuiLib_Ultimate#64]
if( ::GetKeyState(VK_RBUTTON) < 0 ) uState |= MK_LBUTTON;
		if( ::GetKeyState(VK_LBUTTON) < 0 ) uState |= MK_RBUTTON;

**Comment by qdtroy** [comment]
问题已经修正，谢谢反馈
