### ISSUE TITLE
RichEdit 装入超过 5000行(\r\n) 文本后，滚动条的滚动会出错，拉到最底，文本却停留在中间

### ISSUE THREAD

**Issue by shithappens2016** [qdtroy/DuiLib_Ultimate#65]
作者你好。
我用的是官方版本。
偶然一次RichEdit 装入**超过** 5000行(\r\n) 文本后，发现**滚动条**的滚动会出错，**拉到最底**，文本却**停留在中间**。我看了很久代码，找不出问题所在。不知道你的版本，这个问题有修复过吗？

duilib/duilib#149

**Comment by qdtroy** [comment]
超过5000行，滚动条高度计算会有问题，暂时请不要加载过多文本
