### ISSUE TITLE
vs2017编译失败

### ISSUE THREAD

**Issue by fawdlstty** [qdtroy/DuiLib_Ultimate#74]
[
![tim 20180903212502](https://user-images.githubusercontent.com/7323999/44989268-e9260f00-afbf-11e8-9aff-c252133e8a46.jpg)
](url)

**Comment by fawdlstty** [comment]
duilib项目可以编译成功，但新建项目引用这个项目时，就提示一堆错误了

**Comment by fawdlstty** [comment]
[pull/75](https://github.com/qdtroy/DuiLib_Ultimate/pull/75)提交的pr修复此错误

**Comment by fawdlstty** [comment]
#75

**Comment by qdtroy** [comment]
尽快在VS2017分支上修复
