### ISSUE TITLE
菜单的tooltips提示错乱

### ISSUE THREAD

**Issue by xdxiaodong** [qdtroy/DuiLib_Ultimate#8]
当菜单项包含子菜单时，这时候菜单项有设置tooltips属性，子菜单也设置了tooltips属性，如果子菜单的菜单项的坐标跟主菜单的菜单项的坐标重叠（子菜单的菜单项坐标假设为20,20，主菜单的菜单项坐标假设也为20,20），这时候弹出的tooltips是子菜单的而非主菜单的。

**Comment by qdtroy** [comment]
问题收到

**Comment by xdxiaodong** [comment]
当菜单项产生鼠标悬停事件时,如果事件菜单项有子菜单项且事件菜单项与子菜单项在各自窗口的坐标都相同，这时候悬停事件根据鼠标坐标查找的tooltips文本就会是子菜单项的，而非真正产生悬停事件菜单项的tooltips。但是分发DoEvent事件的时候没有错乱，接收DoEvent事件的就是真正产生鼠标悬停事件的菜单项。
