### ISSUE TITLE
win10 开启管理员权限无法拖拽文件

### ISSUE THREAD

**Issue by wangzhechn** [qdtroy/DuiLib_Ultimate#80]
win10上程序开启了管理员权限，然后过滤了以下三条消息还是无法进行文件拖拽，拖拽是显示被禁止，这是为什么呢 ？ChangeWindowMessageFilter(WM_DROPFILES, MSGFLT_ADD);
 ChangeWindowMessageFilter(WM_COPYDATA, MSGFLT_ADD);
 ChangeWindowMessageFilter(0x0049 , MSGFLT_ADD);

**Comment by wangzhechn** [comment]
@tonydevsite 那请问这种问题该如何解决呢

**Comment by qdtroy** [comment]
已经修复

**Comment by zhangyuxue** [comment]
如何解决的大神
