### ISSUE TITLE
编译警告

### ISSUE THREAD

**Issue by chinajeffery** [qdtroy/DuiLib_Ultimate#83]
# warning C4458: “****”的声明隐藏了类成员
代码里面很多类似这样的写法：
```c++
SIZE m_cxyFixed = CScrollBarUI::m_cxyFixed;
```

不仅导致编译警告，而且影响代码的可读性和可维护性。

# warning C4706: 条件表达式内的赋值
```c++
while( pParent = pParent->GetParent() ) {

}
```

**Comment by chinajeffery** [comment]
`
	void CTxtWinHost::SetWordWrap(BOOL fWordWrap)
	{
		fWordWrap = fWordWrap;
		pserv->OnTxPropertyBitsChange(TXTBIT_WORDWRAP, fWordWrap ? TXTBIT_WORDWRAP : 0);
	}
`

**Comment by qdtroy** [comment]
Bug修正，去掉部分警告
