### ISSUE TITLE
demo有内存泄露

### ISSUE THREAD

**Issue by wxr-vbox** [qdtroy/DuiLib_Ultimate#9]
内存泄露严重

**Comment by qdtroy** [comment]
能指出什么地方吗

**Comment by wxr-vbox** [comment]
![111](https://cloud.githubusercontent.com/assets/16031886/11519134/87b6d29c-98d2-11e5-9688-6e0006b7a738.png)

**Comment by qdtroy** [comment]
我排查一下，程序退出时不影响正常使用，不会导致程序运行内存泄漏
