### ISSUE TITLE
我也有自己管理的开发群，有客户在群里发布需求，大家都是平等的机会，我没有因为谁接了项目就把谁踢出群，我只是不定期的清理3年以上不发言的群友，

### ISSUE THREAD

**Issue by craigtao** [qdtroy/DuiLib_Ultimate#95]
我也有自己管理的开发群，有客户在群里发布需求，大家都是平等的机会，我没有因为谁接了项目就把谁踢出群，我只是不定期的清理3年以上不发言的群友，

把想学习和提问的机会留给 现在有需要的人， 群主的做法，我只想奉劝一句“不要这样行事，要对得起良心”

**Comment by qdtroy** [comment]
群内信息我@全部N次了，本群内禁止私自接项目，所有项目在qq群：489436819统一分发！

**Comment by craigtao** [comment]
那你怎么知道我接了呢？ 因为你没有接到，我只是在群里说了句话，
