### ISSUE TITLE
更新界面中的特性问题

### ISSUE THREAD

**Issue by fawdlstty** [qdtroy/DuiLib_Ultimate#96]
**Describe the bug**
在不停刷新的窗口中，通过鼠标左键点击空白处，将导致刷新过程暂停一秒

**To Reproduce**
1. 首先有一个线程，不停往主窗口发自定义消息
2. 窗口（caption="0,0,0,-1"）线程收到自定义消息后，对某一个Control调用Invalidate
3. 指定的Control重载了绘制消息，然后绘制自定义图片，类似于播放视频
4. 这时候对指定Control区域或窗口内的所有不响应点击事件的区域进行鼠标左键单击（不放开），可以很明显感受到窗口播放过程卡了一秒。
5. 假如点击后立即放开或立即拖动，那么卡顿只有一瞬间

**Expected behavior**
预期没有任何卡顿

**Screenshots**
暂时无法演示

**Desktop (please complete the following information):**
 - OS: Win7 x64 专业版
 - Version: 7601

**Additional context**
无

**Comment by qdtroy** [comment]
消息过多过密会卡住消息队列

**Comment by fawdlstty** [comment]
没有卡住队列；不停刷新只是为了验证这个卡顿的问题
