### ISSUE TITLE
FadeButton 用于最小化按钮时，最小化后再还原窗口， 按钮还是hot状态

### ISSUE THREAD

**Issue by 821104180** [qdtroy/DuiLib_Ultimate#99]

**Comment by owhao** [comment]
把SendMessage(WM_SYSCOMMAND, SC_MINIMIZE, 0); 修改为PostMessage(WM_SYSCOMMAND, SC_MINIMIZE, 0);

**Comment by 821104180** [comment]
else if( msg.pSender == m_pMinBtn ) { 
			PostMessage(WM_MOUSELEAVE);
			PostMessage(WM_SYSCOMMAND, SC_MINIMIZE, 0); return; }
demo处修改成这样时, 最小化还原后,最小化按钮为hot状态,当鼠标移动到界面内,hot状态逐渐转化为normal状态, 比之前鼠标移动到最小化按钮上才转化稍好,不过还是有问题

**Comment by qdtroy** [comment]
可以自己刷新一下

**Comment by HuaTianSoft** [comment]
遇到了同样的问题, 尝试过了 PostMessage(WM_MOUSELEAVE);无果,
然后,也试过了刷新, 我是在OnSize后进行刷新的,但是,  也没啥用.
`


LRESULT CMainWnd::OnSize(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{

    if (m_pm.FindControl(_T("maxbtn")) != NULL) m_pm.FindControl(_T("maxbtn"))->Invalidate();
    if (m_pm.FindControl(_T("restorebtn")) != NULL) m_pm.FindControl(_T("restorebtn"))->Invalidate();
    if (m_pm.FindControl(_T("minbtn")) != NULL) m_pm.FindControl(_T("minbtn"))->Invalidate();

    if (m_pm.FindControl(_T("minbtn")) != NULL) m_pm.FindControl(_T("minbtn"))->SetFocus();

    __super::OnSize(uMsg, wParam, lParam, bHandled);
    return 0;
}
`

**Comment by HuaTianSoft** [comment]
算是凑活着解决了, 使用了定时器,OnSize之后,启动定时器,到时后刷新一遍 最大化, 最小化, 还原按钮...

**Comment by qdtroy** [comment]
最新版已经修复
